FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./

# Instale sqlite3 para testes
RUN apk add --no-cache sqlite
RUN npm ci --include=dev

# Instale sqlite3 para TypeORM
RUN npm install sqlite3

COPY . .

RUN npm run build

CMD ["npm", "run", "test:e2e"]